// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbs1_TBDZB2pRmCrnenbZR2c37MruBuNI',
    appId: '1:821023551593:web:465759c34f4290d683f2f8',
    messagingSenderId: '821023551593',
    projectId: 'mytrainningpath-1a36f',
    authDomain: 'mytrainningpath-1a36f.firebaseapp.com',
    storageBucket: 'mytrainningpath-1a36f.firebasestorage.app',
    measurementId: 'G-KXWG0PSH5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcvm9Zt8kaCXtCTL-dsSKhvfjgpvzxO2E',
    appId: '1:821023551593:android:0d24a1a21d3e886083f2f8',
    messagingSenderId: '821023551593',
    projectId: 'mytrainningpath-1a36f',
    storageBucket: 'mytrainningpath-1a36f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_JbWF52SWC8iE_xM2Ciz2nBL81HJ2QBw',
    appId: '1:821023551593:ios:be5366563d74000c83f2f8',
    messagingSenderId: '821023551593',
    projectId: 'mytrainningpath-1a36f',
    storageBucket: 'mytrainningpath-1a36f.firebasestorage.app',
    iosBundleId: 'com.example.myTrainningPath',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_JbWF52SWC8iE_xM2Ciz2nBL81HJ2QBw',
    appId: '1:821023551593:ios:be5366563d74000c83f2f8',
    messagingSenderId: '821023551593',
    projectId: 'mytrainningpath-1a36f',
    storageBucket: 'mytrainningpath-1a36f.firebasestorage.app',
    iosBundleId: 'com.example.myTrainningPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbs1_TBDZB2pRmCrnenbZR2c37MruBuNI',
    appId: '1:821023551593:web:a8b950dd0c0c230f83f2f8',
    messagingSenderId: '821023551593',
    projectId: 'mytrainningpath-1a36f',
    authDomain: 'mytrainningpath-1a36f.firebaseapp.com',
    storageBucket: 'mytrainningpath-1a36f.firebasestorage.app',
    measurementId: 'G-2JSTM8MV2F',
  );
}
